# Generated by Django 3.2.4 on 2021-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_score',
            old_name='candidate',
            new_name='candi',
        ),
    ]
