# Generated by Django 3.2.4 on 2021-06-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_test_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_round_score', models.FloatField()),
                ('second_round_score', models.FloatField()),
                ('third_round_score', models.FloatField()),
                ('candi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
            ],
        ),
    ]
